/**
 * GridMapLoader - Reads GIKI Campus Map from File
 * 
 * This module loads the campus grid from a text file generated by Grid.cpp.
 * It provides validation, error handling, and visualization capabilities.
 * 
 * File Format Expected:
 *   Line 1: ROWS COLS (e.g., "80 80")
 *   Lines 2+: Space-separated integers (0, 1, 2, or 3)
 * 
 * DSA Course Project - GIKI Institute
 */

#include <iostream>
#include <fstream>
#include <vector>
#include <string>

using namespace std;

// ============ CELL TYPE CONSTANTS ============
const int CELL_FREE_PATH = 0;
const int CELL_BUILDING = 1;
const int CELL_NO_FLY_ZONE = 2;
const int CELL_HAZARD = 3;

// ============ GRID MAP LOADER CLASS ============
class GridMapLoader {
private:
    int rows;
    int cols;
    vector<vector<int> > grid;
    bool loaded;
    string filename;

public:
    // Constructor
    GridMapLoader() : rows(0), cols(0), loaded(false), filename("") {}
    
    // Destructor
    ~GridMapLoader() {
        grid.clear();
    }
    
    // Load grid from file
    bool loadFromFile(const char* file) {
        filename = file;
        ifstream inFile(file);
        
        // Check if file exists and opened successfully
        if (!inFile.is_open()) {
            cout << "Error: Cannot open file '" << file << "'" << endl;
            return false;
        }
        
        // Read dimensions from first line
        if (!(inFile >> rows >> cols)) {
            cout << "Error: Failed to read grid dimensions from file." << endl;
            inFile.close();
            return false;
        }
        
        // Validate dimensions
        if (rows <= 0 || cols <= 0) {
            cout << "Error: Invalid grid dimensions (" << rows << " x " << cols << ")" << endl;
            inFile.close();
            return false;
        }
        
        // Allocate grid memory once (memory efficient)
        grid.clear();
        grid.resize(rows, vector<int>(cols, 0));
        
        // Read grid values
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                if (!(inFile >> grid[i][j])) {
                    cout << "Error: Missing data at row " << i << ", col " << j << endl;
                    inFile.close();
                    loaded = false;
                    return false;
                }
                
                // Validate cell value (must be 0, 1, 2, or 3)
                if (grid[i][j] < 0 || grid[i][j] > 3) {
                    cout << "Error: Invalid cell value " << grid[i][j] 
                         << " at (" << i << "," << j << ")" << endl;
                    inFile.close();
                    loaded = false;
                    return false;
                }
            }
        }
        
        inFile.close();
        loaded = true;
        
        cout << "Successfully loaded grid from '" << file << "'" << endl;
        cout << "Grid size: " << rows << " x " << cols << endl;
        
        return true;
    }
    
    // Check if grid is loaded
    bool isLoaded() const {
        return loaded;
    }
    
    // Get number of rows
    int getRows() const {
        return rows;
    }
    
    // Get number of columns
    int getCols() const {
        return cols;
    }
    
    // Get cell value at (r, c)
    int getCellValue(int r, int c) const {
        if (!loaded) {
            cout << "Error: Grid not loaded." << endl;
            return -1;
        }
        if (r < 0 || r >= rows || c < 0 || c >= cols) {
            cout << "Error: Position (" << r << "," << c << ") out of bounds." << endl;
            return -1;
        }
        return grid[r][c];
    }
    
    // Check if cell is within bounds
    bool isInBounds(int r, int c) const {
        return (r >= 0 && r < rows && c >= 0 && c < cols);
    }
    
    // Check if cell is free path
    bool isFree(int r, int c) const {
        return isInBounds(r, c) && grid[r][c] == CELL_FREE_PATH;
    }
    
    // Check if cell is building/obstacle
    bool isObstacle(int r, int c) const {
        return isInBounds(r, c) && grid[r][c] == CELL_BUILDING;
    }
    
    // Check if cell is no-fly zone
    bool isNoFlyZone(int r, int c) const {
        return isInBounds(r, c) && grid[r][c] == CELL_NO_FLY_ZONE;
    }
    
    // Check if cell is hazard
    bool isHazard(int r, int c) const {
        return isInBounds(r, c) && grid[r][c] == CELL_HAZARD;
    }
    
    // Visualize first 20x20 section of loaded map
    void visualizeLoadedMap() const {
        if (!loaded) {
            cout << "Error: No grid loaded to visualize." << endl;
            return;
        }
        
        int displayRows = (rows < 20) ? rows : 20;
        int displayCols = (cols < 20) ? cols : 20;
        
        cout << "\n========== LOADED MAP (First " << displayRows << "x" << displayCols << ") ==========" << endl;
        cout << "Legend: . = Free, # = Building, N = No-Fly, H = Hazard" << endl;
        cout << endl;
        
        // Print column numbers
        cout << "    ";
        for (int j = 0; j < displayCols; j++) {
            cout << (j % 10);
        }
        cout << endl;
        
        // Print grid with row numbers
        for (int i = 0; i < displayRows; i++) {
            // Row number
            if (i < 10) cout << " ";
            cout << i << "  ";
            
            // Grid cells
            for (int j = 0; j < displayCols; j++) {
                char symbol;
                switch (grid[i][j]) {
                    case CELL_FREE_PATH:   symbol = '.'; break;
                    case CELL_BUILDING:    symbol = '#'; break;
                    case CELL_NO_FLY_ZONE: symbol = 'N'; break;
                    case CELL_HAZARD:      symbol = 'H'; break;
                    default:               symbol = '?'; break;
                }
                cout << symbol;
            }
            cout << endl;
        }
        cout << "======================================================" << endl;
    }
    
    // Visualize full map
    void visualizeFullMap() const {
        if (!loaded) {
            cout << "Error: No grid loaded to visualize." << endl;
            return;
        }
        
        cout << "\n========== FULL LOADED MAP (" << rows << "x" << cols << ") ==========" << endl;
        cout << "Legend: . = Free, # = Building, N = No-Fly, H = Hazard" << endl;
        
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                char symbol;
                switch (grid[i][j]) {
                    case CELL_FREE_PATH:   symbol = '.'; break;
                    case CELL_BUILDING:    symbol = '#'; break;
                    case CELL_NO_FLY_ZONE: symbol = 'N'; break;
                    case CELL_HAZARD:      symbol = 'H'; break;
                    default:               symbol = '?'; break;
                }
                cout << symbol;
            }
            cout << endl;
        }
        cout << "======================================================" << endl;
    }
    
    // Print statistics about loaded grid
    void printStats() const {
        if (!loaded) {
            cout << "Error: No grid loaded." << endl;
            return;
        }
        
        int freeCells = 0, buildings = 0, noFlyZones = 0, hazards = 0;
        
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                switch (grid[i][j]) {
                    case CELL_FREE_PATH:   freeCells++; break;
                    case CELL_BUILDING:    buildings++; break;
                    case CELL_NO_FLY_ZONE: noFlyZones++; break;
                    case CELL_HAZARD:      hazards++; break;
                }
            }
        }
        
        cout << "\n========== GRID STATISTICS ==========" << endl;
        cout << "File: " << filename << endl;
        cout << "Dimensions: " << rows << " x " << cols << endl;
        cout << "Total Cells: " << (rows * cols) << endl;
        cout << "Free Paths: " << freeCells << " (" << (freeCells * 100 / (rows * cols)) << "%)" << endl;
        cout << "Buildings: " << buildings << " (" << (buildings * 100 / (rows * cols)) << "%)" << endl;
        cout << "No-Fly Zones: " << noFlyZones << " (" << (noFlyZones * 100 / (rows * cols)) << "%)" << endl;
        cout << "Hazards: " << hazards << " (" << (hazards * 100 / (rows * cols)) << "%)" << endl;
        cout << "=====================================" << endl;
    }
    
    // Get pointer to grid (for external use)
    const vector<vector<int> >& getGrid() const {
        return grid;
    }
};

// ============ MAIN FUNCTION ============
int main() {
    ios_base::sync_with_stdio(false);
    
    cout << "=== GIKI Campus Grid Loader ===" << endl;
    cout << endl;
    
    // Create loader instance
    GridMapLoader loader;
    
    // Try to load the campus map
    if (!loader.loadFromFile("giki_map.txt")) {
        cout << "Failed to load map. Please run Grid.cpp first to generate giki_map.txt" << endl;
        return 1;
    }
    
    // Print statistics
    loader.printStats();
    
    // Visualize first 20x20 section
    loader.visualizeLoadedMap();
    
    // Test cell access
    cout << "\n=== Cell Access Tests ===" << endl;
    
    // Test some specific cells
    int testCells[][2] = {{0, 0}, {40, 40}, {74, 40}, {15, 35}, {10, 35}};
    
    for (int i = 0; i < 5; i++) {
        int r = testCells[i][0];
        int c = testCells[i][1];
        int val = loader.getCellValue(r, c);
        
        cout << "Cell (" << r << "," << c << "): ";
        switch (val) {
            case CELL_FREE_PATH:   cout << "Free Path"; break;
            case CELL_BUILDING:    cout << "Building"; break;
            case CELL_NO_FLY_ZONE: cout << "No-Fly Zone"; break;
            case CELL_HAZARD:      cout << "Hazard"; break;
            default:               cout << "Unknown"; break;
        }
        cout << endl;
    }
    
    // Test boundary checks
    cout << "\n=== Boundary Tests ===" << endl;
    cout << "Is (0,0) in bounds? " << (loader.isInBounds(0, 0) ? "Yes" : "No") << endl;
    cout << "Is (79,79) in bounds? " << (loader.isInBounds(79, 79) ? "Yes" : "No") << endl;
    cout << "Is (80,80) in bounds? " << (loader.isInBounds(80, 80) ? "Yes" : "No") << endl;
    cout << "Is (-1,0) in bounds? " << (loader.isInBounds(-1, 0) ? "Yes" : "No") << endl;
    
    // Test cell type checks
    cout << "\n=== Cell Type Tests ===" << endl;
    cout << "Is (5,5) free? " << (loader.isFree(5, 5) ? "Yes" : "No") << endl;
    cout << "Is (0,0) obstacle? " << (loader.isObstacle(0, 0) ? "Yes" : "No") << endl;
    cout << "Is (10,35) no-fly zone? " << (loader.isNoFlyZone(10, 35) ? "Yes" : "No") << endl;
    
    cout << "\nGrid loading complete!" << endl;
    
    return 0;
}

